Repository openedx/paragon, pull requests merged in 2018-03, with the labels that each got.

#162 style(import): remove unnecessary Hyperlink import
  src/Hyperlink/Hyperlink.stories.jsx
Labels: ready for review

#166 docs(button): update Button story
  .storybook/__snapshots__/Storyshots.test.js.snap
  src/Button/Button.stories.jsx
Labels: ready for review

#168 docs(mailtolink-story): add storybook addons
  .storybook/__snapshots__/Storyshots.test.js.snap
  src/MailtoLink/MailtoLink.stories.jsx
Labels: ready for review

#173 docs(icon-add-ons): add add-ons
  .storybook/__snapshots__/Storyshots.test.js.snap
  src/Icon/Icon.stories.jsx
Labels: ready for review

#178 fix(build): builds are now es5 compliant
  package-lock.json
  package.json
Labels: ready for discussion, ready for review

#177 refactor(es-check): use es-check to validate es5
  .travis.yml
  package-lock.json
  package.json
Labels: ready for discussion

#156 Pass Disabled prop down in InputText
  .storybook/__snapshots__/Storyshots.test.js.snap
  package-lock.json
  package.json
  src/InputSelect/InputSelect.stories.jsx
  src/InputSelect/index.jsx
Labels: ready for review

#185 fix(email-prop-type): upgrade to IE11 compatible version
  package-lock.json
  package.json
Labels: ready for review
