Repository openedx/paragon, pull requests merged in 2022-06, with the labels that each got.

#1246 [BD-46] feat: algolia search
  www/package-lock.json
  www/package.json
  www/src/components/Header.jsx
  www/src/components/Seach.jsx
  www/src/components/Search.scss
  www/src/scss/base.scss
  www/src/templates/component-page-template.jsx
Labels: needs triage, blended

#1359 [BD-46] docs: fixing the Header menu in RTL format
  www/src/components/Header.jsx
  www/src/components/LinkedHeading.scss
Labels: needs triage, blended

#1331 [BD-46] docs: Header z-index increase
  www/src/components/Header.jsx
  www/src/components/Header.scss
  www/src/scss/_variables.scss
  www/src/scss/base.scss
  www/src/scss/edxorg-theme.scss
  www/src/scss/openedx-theme.scss
Labels: needs triage, blended

#1333 [BD-46] docs: fixing the number of columns in the All Components menu
  www/src/components/Menu.scss
Labels: needs triage, blended

#1358 [BD-46] feat: refactoring mobile view Breadcrumbs component
  src/Breadcrumb/README.md
Labels: needs triage, blended

#1334 [BD-46] docs: fixed margin buttons
  src/Button/README.md
Labels: needs triage, blended

#1336 [BD-46] fix: fixed Icon button component
  src/IconButton/README.md
Labels: needs triage, blended

#1335 [BD-46] fix: fixed Sheet button gaps
  src/Sheet/README.md
Labels: needs triage, blended

#1337 [BD-46] docs: fixed action row checkbox
  src/ActionRow/README.md
Labels: needs triage, blended

#1367 [BD-46] chore: remove airbnb-prop-types dependency and upgrade eslint in docs project
  package-lock.json
  package.json
  src/DataTable/index.jsx
  src/ListBox/index.jsx
  src/Modal/AlertModal.jsx
  src/Modal/MarketingModal.jsx
  src/Pagination/index.jsx
  src/utils/propTypes/greaterThan.js
  src/utils/propTypes/index.js
  src/utils/propTypes/nonNegativeInteger.js
  src/utils/propTypes/utils.js
  www/package-lock.json
  www/package.json
  www/src/components/PropsTable.jsx
Labels: needs triage, blended

#1341 docs: [BD-46] added "Elevation" page to "Foundations" section
  scss/core/_utilities.scss
  scss/core/_variables.scss
  www/package-lock.json
  www/src/components/Menu.jsx
  www/src/components/_doc-elements.scss
  www/src/pages/foundations/elevation.jsx
Labels: blended

#1364 [BD-46] feat: added a new box-shadow for the Card component
  src/Card/Card.scss
Labels: needs triage, blended

#1100 [BD-46] feat: implement i18n in Paragon components and in docs site
  .gitignore
  .tx/config
  Makefile
  README.md
  docs/decisions/0015-i18n-support.rst
  example/package-lock.json
  example/package.json
  package-lock.json
  package.json
  src/Alert/Alert.test.jsx
  src/Alert/index.jsx
  src/DataTable/DataTableLayout.jsx
  src/DataTable/ExpandAll.jsx
  src/DataTable/FilterStatus.jsx
  src/DataTable/RowStatus.jsx
  src/DataTable/SidebarFilters.jsx
  src/DataTable/selection/BaseSelectionStatus.jsx
  src/DataTable/selection/ControlledSelectionStatus.jsx
  src/DataTable/selection/SelectionStatus.jsx
  src/DataTable/selection/tests/ControlledSelectionStatus.test.jsx
  src/DataTable/selection/tests/SelectionStatus.test.jsx
  src/DataTable/tests/DataTable.test.jsx
  src/DataTable/tests/ExpandAll.test.jsx
  src/DataTable/tests/FilterStatus.test.jsx
  src/DataTable/tests/RowStatus.test.jsx
  src/DataTable/tests/SmartStatus.test.jsx
  src/Toast/Toast.test.jsx
  src/Toast/index.jsx
  src/i18n/index.js
  src/i18n/messages/ar.json
  src/i18n/messages/ca.json
  src/i18n/messages/es_419.json
  src/i18n/messages/fr.json
  src/i18n/messages/he.json
  src/i18n/messages/id.json
  src/i18n/messages/ko_KR.json
  src/i18n/messages/pl.json
  src/i18n/messages/pt_BR.json
  src/i18n/messages/ru.json
  src/i18n/messages/th.json
  src/i18n/messages/uk.json
  src/i18n/messages/zh_CN.json
  src/index.js
  www/.env.development
  www/gatsby-node.js
  www/package-lock.json
  www/package.json
  www/src/components/CodeBlock.jsx
  www/src/components/PropsTable.jsx
  www/src/components/Settings.jsx
  www/src/config.js
  www/src/context/SettingsContext.jsx
  www/src/utils/hasFeatureFlagEnabled.js
Labels: blended

#1202 [BD-46] docs: added focus state in components
  src/Breadcrumb/Breadcrumb.scss
  src/Breadcrumb/_variables.scss
  src/Chip/Chip.scss
  src/Chip/_variables.scss
  src/Form/_Form.scss
  src/Form/_variables.scss
  src/Pagination/Pagination.scss
  src/Pagination/_variables.scss
  src/SearchField/SearchField.scss
  src/SearchField/_variables.scss
Labels: blended, raccoon-gang

#1362 [BD-46] feat: fixed SelectableBox responsiveness
  src/SelectableBox/README.md
Labels: needs triage, blended

#1363 feat: [BD-46] adding caret for ModalPopup component
  src/Modal/Modal.scss
  src/Modal/ModalPopup.jsx
  src/Modal/ModalPopup.test.jsx
  src/Modal/modal-popup.mdx
Labels: blended

#1405 [BD-46] build: update i18n script to compile messages pulled from transifex
  .tx/config
  Makefile
  package.json
Labels: blended

#1378 [BD-46] docs: improve design and usability of Icons page
  src/SearchField/index.jsx
  www/package-lock.json
  www/package.json
  www/src/components/IconsTable.jsx
  www/src/components/IconsTable.scss
  www/src/scss/base.scss
Labels: blended

#1377 [BD-46] docs: deprecate CardDeck
  src/Card/README.md
Labels: blended

#1381 [BD-46] docs: refactoring Card component on the mobile page styles #1314
  src/Card/Card.scss
  src/Card/README.md
Labels: blended

#1401 [BD-46] docs: The weird title text was removed
  www/package-lock.json
  www/package.json
Labels: blended
