Repository openedx/paragon, pull requests merged in 2022-03, with the labels that each got.

#1096 [BD-46] feat: implement Sticky component
  src/Sticky/README.md
  src/Sticky/Sticky.scss
  src/Sticky/Sticky.test.jsx
  src/Sticky/__snapshots__/Sticky.test.jsx.snap
  src/Sticky/_variables.scss
  src/Sticky/index.jsx
  src/index.js
  src/index.scss
Labels: needs triage, blended

#1101 feat: [BD-46] update card docs with content block empty
  src/Card/README.md
Labels: needs triage, blended

#1126 [BD-46] feat: SelectMenu own page
  package-lock.json
  src/Menu/Menu.scss
  src/Menu/README.md
  src/Menu/SelectMenu.jsx
  src/Menu/SelectMenu.test.jsx
  src/Menu/__snapshots__/SelectMenu.test.jsx.snap
  src/Menu/select-menu.md
Labels: needs triage, blended

#1138 feat: add outline variant of verified icon, rename previous icon [PAR-700]
  icons/es5/VerifiedBadgeOutline.js
  icons/es5/VerifiedOutline.js
  icons/es5/index.js
  icons/jsx/VerifiedBadgeOutline.jsx
  icons/jsx/VerifiedOutline.jsx
  icons/jsx/index.jsx
  icons/svg/verified_badge_outline.svg
  icons/svg/verified_outline.svg
Labels: needs triage, open-source-contribution

#1139 feat: add "report" and "report outline" icons [PAR-701] [PAR-702]
  icons/es5/Report.js
  icons/es5/ReportOutline.js
  icons/es5/index.js
  icons/jsx/Report.jsx
  icons/jsx/ReportOutline.jsx
  icons/jsx/index.jsx
  icons/svg/report.svg
  icons/svg/report_outline.svg
Labels: needs triage, open-source-contribution

#1140 feat: add outline variants of "edit", "post", "queston answer", and "school" icons [PAR-703] [PAR-705] [PAR-707] [PAR-710]
  icons/es5/EditOutline.js
  icons/es5/PostOutline.js
  icons/es5/QuestionAnswerOutline.js
  icons/es5/SchoolOutline.js
  icons/es5/index.js
  icons/jsx/EditOutline.jsx
  icons/jsx/PostOutline.jsx
  icons/jsx/QuestionAnswerOutline.jsx
  icons/jsx/SchoolOutline.jsx
  icons/jsx/index.jsx
  icons/svg/edit_outline.svg
  icons/svg/post_outline.svg
  icons/svg/question_answer_outline.svg
  icons/svg/school_outline.svg
Labels: needs triage, open-source-contribution

#1141 feat: add icons for "question" and "people" [PAR-704] [PAR-706]
  icons/es5/People.js
  icons/es5/Question.js
  icons/es5/index.js
  icons/jsx/People.jsx
  icons/jsx/Question.jsx
  icons/jsx/index.jsx
  icons/svg/people.svg
  icons/svg/question.svg
Labels: needs triage, open-source-contribution

#1142 feat: add horizontal variant of more icon, and "issue" and "bookmark" icons [PAR-708] [PAR-709] [PAR-711]
  icons/es5/Bookmark.js
  icons/es5/Issue.js
  icons/es5/MoreHoriz.js
  icons/es5/index.js
  icons/jsx/Bookmark.jsx
  icons/jsx/Issue.jsx
  icons/jsx/MoreHoriz.jsx
  icons/jsx/index.jsx
  icons/svg/bookmark.svg
  icons/svg/issue.svg
  icons/svg/more_horiz.svg
Labels: needs triage, open-source-contribution

#1136 [BD-46] feat: navigation for page headings
  www/gatsby-browser.js
  www/gatsby-config.js
  www/src/components/LinkedHeading.jsx
  www/src/components/LinkedHeading.scss
  www/src/components/PageLayout.jsx
  www/src/components/Toc.jsx
  www/src/components/Toc.scss
  www/src/scss/base.scss
  www/src/templates/component-page-template.jsx
Labels: needs triage, blended

#1159 [BD-46] Improve tree-shaking detectability
  package.json
Labels: open edx community review, blended

#1109 [BD-46] feat: annotated progress bar
  src/ProgressBar/ProgressBar.scss
  src/ProgressBar/README.md
  src/ProgressBar/_variables.scss
  src/ProgressBar/index.jsx
  src/ProgressBar/tests/ProgressBar.test.jsx
  src/ProgressBar/tests/__snapshots__/ProgressBar.test.jsx.snap
  src/ProgressBar/tests/utils.test.js
  src/ProgressBar/utils.js
Labels: needs triage, blended

#1155 feat: [BD-46] adding an extra wrapper, overflow-x scroll
  src/Container/README.md
Labels: needs triage, blended

#1133 [BD-46] feat: add Segment
  www/.env.development
  www/gatsby-config.js
  www/package-lock.json
  www/package.json
  www/src/context/SettingsContext.jsx
  www/src/pages/insights.jsx
Labels: needs triage, blended

#1158 [BD-46] feat: deprecate font-awesome
  package-lock.json
  package.json
  src/Icon/README.md
  src/Icon/index.jsx
  src/IconButton/IconButton.test.jsx
  src/IconButton/README.md
  src/IconButton/index.jsx
  src/IconButtonToggle/IconButtonToggle.test.jsx
  src/IconButtonToggle/README.md
  src/IconButtonToggle/index.jsx
  src/SearchField/SearchField.test.jsx
  src/SearchField/SearchFieldAdvanced.jsx
  src/SearchField/__snapshots__/SearchField.test.jsx.snap
  src/SearchField/index.jsx
  src/Toast/README.md
  src/Toast/index.jsx
  www/src/components/CodeBlock.jsx
Labels: needs triage, blended

#1161 feat: [BD-46] box shadows toolkit
  scss/core/_variables.scss
  src/Alert/Alert.scss
Labels: needs triage, blended

#1143 feat: [BD-46] added prop to manage modals zIndex
  scss/core/_utilities.scss
  src/Modal/Modal.scss
  src/Modal/ModalDialog.jsx
  src/Modal/ModalLayer.jsx
Labels: needs triage, blended

#1172 [BD-46] feat: added sticky header
  www/src/components/Header.jsx
Labels: needs triage, blended

#1175 [BD-46] feat: icon button prop fix
  src/IconButton/IconButton.test.jsx
  src/IconButton/__snapshots__/IconButton.test.jsx.snap
  src/IconButton/index.jsx
Labels: needs triage, blended

#1187 [BD-46] feat: display spacing in pixels
  www/src/pages/foundations/spacing.jsx
Labels: needs triage, blended

#1188 [BD-46] fix: prevent stretching in Stack
  src/Stack/README.md
Labels: needs triage, blended
