Repository openedx/paragon, pull requests merged in 2023-07, with the labels that each got.

#2400 [BD-46] docs: add info about xs min-width
  www/src/pages/foundations/responsive.jsx
Labels: blended

#2442 [BD-46] fix: specific icons fix
  icons/es5/Issue.js
  icons/es5/Question.js
  icons/es5/WarningFilled.js
  icons/jsx/Issue.jsx
  icons/jsx/Question.jsx
  icons/jsx/WarningFilled.jsx
  icons/svg/issue.svg
  icons/svg/question.svg
  icons/svg/warning_filled.svg
Labels: blended, raccoon-gang

#2395 [BD-46] docs: added 'Leave feedback' button to the top of the component page
  www/src/components/LeaveFeedback.scss
  www/src/components/LeaveFeedback.tsx
  www/src/components/PageLayout.tsx
  www/src/scss/base.scss
  www/src/templates/component-page-template.tsx
Labels: blended

#2441 fix: make icons package tree-shakeable
  icons/package.json
Labels: open-source-contribution

#2408 removed duplication of components import
  src/ActionRow/_index.scss
  src/Alert/index.scss
  src/Annotation/index.scss
  src/Avatar/index.scss
  src/AvatarButton/index.scss
  src/Badge/index.scss
  src/Breadcrumb/index.scss
  src/Bubble/index.scss
  src/Button/index.scss
  src/Card/index.scss
  src/Carousel/index.scss
  src/Chip/index.scss
  src/CloseButton/index.scss
  src/Code/index.scss
  src/Collapsible/index.scss
  src/ColorPicker/index.scss
  src/DataTable/index.scss
  src/Dropdown/index.scss
  src/Dropzone/index.scss
  src/Fieldset/index.scss
  src/Figure/index.scss
  src/Form/_index.scss
  src/Hyperlink/index.scss
  src/Icon/index.scss
  src/IconButton/index.scss
  src/IconButtonToggle/index.scss
  src/Image/index.scss
  src/Media/index.scss
  src/Menu/index.scss
  src/Modal/index.scss
  src/Nav/index.scss
  src/Navbar/index.scss
  src/OverflowScroll/index.scss
  src/PageBanner/index.scss
  src/Pagination/index.scss
  src/Popover/index.scss
  src/ProgressBar/index.scss
  src/Scrollable/index.scss
  src/SearchField/index.scss
  src/SelectableBox/index.scss
  src/Sheet/index.scss
  src/Skeleton/index.scss
  src/Spinner/index.scss
  src/Stack/index.scss
  src/StatefulButton/index.scss
  src/Stepper/index.scss
  src/Sticky/index.scss
  src/Table/index.scss
  src/Tabs/index.scss
  src/Toast/index.scss
  src/Tooltip/index.scss
  src/TransitionReplace/index.scss
  src/ValidationMessage/index.scss
  src/index.scss
Labels: open-source-contribution

#2377 [BD-46] fix: fixed odd trapezoid-like underline on active tab in Tabs component
  src/Nav/_mixins.scss
  src/Nav/_variables.scss
  src/Nav/index.scss
  src/Tabs/_variables.scss
  src/Tabs/index.scss
Labels: blended

#2453 [BD-46] fix: initial autoResize functionality
  src/Form/FormControl.jsx
  src/Form/tests/FormControl.test.jsx
Labels: blended, raccoon-gang
