Repository openedx/paragon, pull requests merged in 2023-08, with the labels that each got.

#2477 [BD-46] feat: added arrow bg color for Popover component
  src/Popover/_mixins.scss
  src/Popover/index.scss
Labels: raccoon-gang

#2495 [BD-46] feat: renamed custom media query
  src/Card/Card.scss
  src/ColorPicker/ColorPicker.scss
  src/DataTable/DataTable.scss
  src/Form/_Form.scss
  src/ProductTour/Checkpoint.scss
  src/Toast/Toast.scss
  src/Toast/ToastContainer.scss
  styles/css/core/custom-media-breakpoints.css
  tokens/style-dictionary.js
  tokens/utils.js
  www/src/components/Menu.scss
  www/src/components/Search/Search.scss
  www/src/components/_doc-elements.scss
  www/src/components/header/Header.scss
Labels: blended

#2496 [BD-46] fix: fixed rounded corners for Card.ImageCap component
  src/Card/index.scss
Labels: bug, blended, raccoon-gang

#2378 [BD-46] feat: create chip carousel
  component-generator/constants.js
  component-generator/templates/index.scss
  component-generator/utils.js
  src/Chip/README.md
  src/ChipCarousel/ChipCarousel.test.jsx
  src/ChipCarousel/README.md
  src/ChipCarousel/_variables.scss
  src/ChipCarousel/index.scss
  src/ChipCarousel/index.tsx
  src/ChipCarousel/messages.js
  src/Icon/index.d.ts
  src/OverflowScroll/OverflowScroll.jsx
  src/index.js
  src/index.scss
Labels: blended, raccoon-gang

#2511 [BD-46] fix: fixed border-radius of the card img
  src/Card/_variables.scss
  src/Card/index.scss
Labels: blended

#2527 [BD-46] fix: fixed Gatsby local build
  www/gatsby-config.js
Labels: bug, blended

#2525 fix(deps): OEP65. updating to react-intl 6.4.4
  package-lock.json
  package.json
Labels: open-source-contribution

#2460 [BD-46] feat: add paragon-cli
  bin/install-theme.js
  bin/paragon-scripts.js
  example/package.json
  example/src/index.scss
  package-lock.json
  package.json
Labels: blended

#2451 feat: maximum selectable rows on the Datatable
  src/DataTable/README.md
  src/DataTable/index.jsx
  src/DataTable/selection/BaseSelectionStatus.jsx
  src/DataTable/tests/CardView.test.jsx
  src/DataTable/utils/getVisibleColumns.jsx
  src/DataTable/utils/tests/selectColumn.test.jsx
Labels: open-source-contribution

#2013 [BD-46] feat: table of content for non-components
  example/src/MyComponent.jsx
  package-lock.json
  www/.env.development
  www/package.json
  www/src/components/AutoToc.tsx
  www/src/components/IconsTable.scss
  www/src/components/IconsTable.tsx
  www/src/components/PageLayout.tsx
  www/src/pages/foundations/colors.tsx
  www/src/pages/foundations/elevation.jsx
  www/src/pages/foundations/responsive.jsx
  www/src/pages/foundations/spacing.tsx
  www/src/pages/foundations/typography.tsx
  www/src/pages/insights.tsx
  www/src/pages/status.tsx
  www/src/templates/default-mdx-page-template.tsx
Labels: blended

#2531 [BD-46] fix: skeleton.css for both dev and prod
  scss/core/core.scss
Labels: blended, raccoon-gang

#2479 docs: update documentation for deprecated components
  src/CheckBoxGroup/README.md
  src/InputSelect/README.md
  src/InputText/README.md
  src/RadioButtonGroup/README.md
  src/Table/README.md
  src/TextArea/README.md
Labels: open-source-contribution
