Repository openedx/paragon, pull requests merged in 2023-11, with the labels that each got.

#2758 [BD-46] feat: add i18n support for ProductTour Checkpoint sr-only message
  package.json
  src/ProductTour/Checkpoint.jsx
  src/ProductTour/Checkpoint.test.jsx
  src/ProductTour/ProductTour.test.jsx
  src/i18n/messages/ar.json
  src/i18n/messages/ca.json
  src/i18n/messages/es_419.json
  src/i18n/messages/es_AR.json
  src/i18n/messages/es_ES.json
  src/i18n/messages/fr.json
  src/i18n/messages/he.json
  src/i18n/messages/id.json
  src/i18n/messages/it_IT.json
  src/i18n/messages/ko_KR.json
  src/i18n/messages/pl.json
  src/i18n/messages/pt_BR.json
  src/i18n/messages/pt_PT.json
  src/i18n/messages/ru.json
  src/i18n/messages/th.json
  src/i18n/messages/tr_TR.json
  src/i18n/messages/uk.json
  src/i18n/messages/zh_CN.json
Labels: blended

#2617 [BD-46] feat: added Segment track for CLI scripts
  bin/paragon-scripts.js
  component-generator/index.js
  component-generator/utils.js
  package-lock.json
  package.json
  utils.js
  www/netlify/functions/sendAnalyticsData.js
  www/netlify/functions/trackGenerateComponent.js
Labels: blended

#2795 [BD-46] chore: sync alpha to master
  .github/workflows/release.yml
  README.md
  bin/paragon-scripts.js
  dependent-usage.json
  example/package.json
  icons/es5/VideocamOutlined.js
  icons/es5/index.js
  icons/jsx/VideocamOutlined.jsx
  icons/jsx/index.jsx
  icons/svg/videocam_outlined.svg
  lib/install-theme.js
  package-lock.json
  package.json
  src/Breadcrumb/README.md
  src/DataTable/FilterStatus.jsx
  src/DataTable/tests/FilterStatus.test.jsx
  src/DataTable/tests/SmartStatus.test.jsx
  src/Menu/README.md
  src/ProductTour/Checkpoint.jsx
  src/ProductTour/Checkpoint.test.jsx
  src/ProductTour/ProductTour.test.jsx
  src/SelectableBox/tests/SelectableBoxSet.test.jsx
  src/i18n/messages/ar.json
  src/i18n/messages/ca.json
  src/i18n/messages/es_419.json
  src/i18n/messages/es_AR.json
  src/i18n/messages/es_ES.json
  src/i18n/messages/fr.json
  src/i18n/messages/he.json
  src/i18n/messages/id.json
  src/i18n/messages/it_IT.json
  src/i18n/messages/ko_KR.json
  src/i18n/messages/pl.json
  src/i18n/messages/pt_BR.json
  src/i18n/messages/pt_PT.json
  src/i18n/messages/ru.json
  src/i18n/messages/th.json
  src/i18n/messages/tr_TR.json
  src/i18n/messages/uk.json
  src/i18n/messages/zh_CN.json
  www/package.json
  www/src/components/Menu.tsx
  www/src/scss/openedx-theme.scss
Labels: blended

#2812 [BD-46] fix: remove props spreading in `DataTable` components
  src/DataTable/ExpandRow.jsx
  src/DataTable/selection/ControlledSelect.jsx
  src/DataTable/selection/ControlledSelectHeader.jsx
  src/DataTable/selection/ControlledSelectionStatus.jsx
  src/DataTable/tests/ExpandRow.test.jsx
Labels: blended

#2814 [BD-46] docs: remove technical documentation label update readme
  README.md
  www/src/components/header/SiteTitle.tsx
  www/src/pages/index.tsx
Labels: blended

#2811 [BD-46] refactor: created missing design tokens
  src/Nav/index.scss
  src/Tabs/index.scss
  styles/css/core/variables.css
  styles/css/themes/light/variables.css
  tokens/src/core/components/Card.json
  tokens/src/core/components/Carousel.json
  tokens/src/core/components/DataTable.json
  tokens/src/core/components/Nav.json
  tokens/src/core/components/ProgressBar.json
  tokens/src/core/components/Tab.json
  tokens/src/themes/light/components/Breadcrumb.json
  tokens/src/themes/light/components/Dropdown.json
  tokens/src/themes/light/components/Form/color.json
  tokens/src/themes/light/components/Nav.json
  tokens/src/themes/light/components/Popover.json
  tokens/src/themes/light/components/ProductTour.json
  tokens/src/themes/light/components/Tab.json
Labels: blended

#2817 [BD-46] refactor: removed unused SCSS variables
  src/Card/_variables.scss
  src/Nav/_variables.scss
  src/Pagination/_variables.scss
  src/SearchField/_variables.scss
Labels: blended

#2807 [BD-46] refactor: replaced set-output in CI/CD configuration
  .github/workflows/ci.yml
Labels: blended

#2820 ci(deploy): Remove pages deploy step
  .github/workflows/release.yml
Labels: open-source-contribution, needs test run

#2791 [BD-46] docs: added keep the menu nav section of viewed page expanded
  src/Avatar/README.md
  src/CheckBox/README.md
  src/Image/README.md
  src/SearchField/README.md
  src/SelectableBox/README.md
  src/Spinner/README.md
  src/Stepper/README.md
  src/Table/README.md
  src/Truncate/README.md
  src/hooks/useIndexOfLastVisibleChild.mdx
  src/hooks/useIsVisible.mdx
  src/hooks/useWindowSize.mdx
  www/src/components/Menu.scss
  www/src/components/Menu.tsx
  www/src/config.js
  www/src/pages/guides/getting-started.mdx
Labels: blended

#2847 [BD-46] chore: sync alpha to master
  .github/workflows/ci.yml
  .github/workflows/release.yml
  dependent-usage.json
  package-lock.json
  src/Avatar/README.md
  src/Form/_index.scss
  src/Image/README.md
  src/SearchField/README.md
  src/SelectableBox/README.md
  src/Spinner/README.md
  src/Stepper/README.md
  src/Truncate/README.md
  src/hooks/useIndexOfLastVisibleChild.mdx
  src/hooks/useIsVisible.mdx
  src/hooks/useWindowSize.mdx
  www/src/components/Menu.scss
  www/src/components/Menu.tsx
  www/src/config.js
  www/src/pages/guides/getting-started.mdx
Labels: blended

#2855 [BD-46] fix: fixed borders for the Dropzone component
  src/Dropzone/_variables.scss
  src/Dropzone/index.scss
Labels: blended

#2858 [BD-46] add loading state to CSS variables table
  styles/scss/core/core.scss
  www/src/components/ComponentVariablesTable.tsx
  www/src/scss/base.scss
Labels: blended

#2838 Improves the DataTable RowStatus [FC-0036]
  src/DataTable/RowStatus.jsx
  src/DataTable/tests/DataTable.test.jsx
  src/DataTable/tests/RowStatus.test.jsx
  src/DataTable/tests/SmartStatus.test.jsx
Labels: open-source-contribution

#2865 [BD-46] docs: added skeleton display on the documentation site
  www/src/scss/base.scss
Labels: blended
