Repository openedx/paragon, pull requests merged in 2023-06, with the labels that each got.

#1649 Paragon vulnerablities resolution
  icons/package.json
  package-lock.json
  www/package.json
Labels: engineering review

#2336 [BD-46] docs: created a Tools section/page on the documentation site
  www/src/components/Menu.scss
  www/src/components/Menu.tsx
  www/src/pages/insights.tsx
  www/src/pages/tools/component-generator.mdx
Labels: blended

#2323 [BD-46] docs: add copy URL and reset buttons to playground page
  package-lock.json
  www/package.json
  www/playroom.config.js
  www/playroom/constants.js
  www/src/components/header/Header.scss
  www/src/components/header/SiteTitle.tsx
  www/src/pages/playground.tsx
Labels: blended

#1988 [BD-46] feat: add ability to use unlabeled Radio and Checkbox components in respective Form sets
  src/Form/FormCheckbox.jsx
  src/Form/FormRadio.jsx
  src/Form/FormRadioSetContext.jsx
  src/Form/form-radio.mdx
  src/Form/index.jsx
  src/SelectableBox/tests/SelectableBox.test.jsx
  src/SelectableBox/tests/__snapshots__/SelectableBox.test.jsx.snap
  src/SelectableBox/tests/__snapshots__/SelectableBoxSet.test.jsx.snap
  src/SelectableBox/tests/utils.test.js
  src/SelectableBox/utils.js
  src/index.js
Labels: blended

#2357 feat: create themes flag to build tokens
  tokens/build-tokens.js
  tokens/utils.js
Labels: open-source-contribution

#2361 [BD-46] feat: added rounded pill token
  styles/css/core/variables.css
  styles/scss/core/_variables.scss
  tokens/src/core/alias/size.json
Labels: blended

#2359 [BD-46] docs: fixed issue feedback error
  src/Figure/README.md
  www/src/components/LeaveFeedback.scss
  www/src/components/LeaveFeedback.tsx
Labels: blended

#2358 [BD-46] feat: removed white background on Stepper.Header component
  src/Stepper/Stepper.scss
  src/Stepper/_variables.scss
Labels: blended

#2309 [BD-46] docs: extended Edx Typescript config
  .github/workflows/commitlint.yml
  package-lock.json
  package.json
  tsconfig.json
Labels: blended

#2151 [BD-46] Add fixed increment scroll behavior to useOverflowScroll
  src/OverflowScroll/OverflowScroll.jsx
  src/OverflowScroll/data/tests/useOverflowScrollActions.test.jsx
  src/OverflowScroll/data/useOverflowScroll.js
  src/OverflowScroll/data/useOverflowScrollActions.js
  src/OverflowScroll/useOverflowScroll.mdx
Labels: blended

#2364 [BD-46] feat: added missing SCSS variables in design tokens
  src/Alert/Alert.scss
  src/Annotation/Annotation.scss
  src/Card/card-bootstrap.scss
  styles/css/core/variables.css
  styles/css/themes/light/variables.css
  styles/scss/core/_variables.scss
  styles/scss/core/bootstrap-override/_mixins.scss
  styles/scss/core/bootstrap-override/mixins/_grid-framework.scss
  styles/scss/core/bootstrap-override/mixins/_grid.scss
  tokens/src/core/components/Spinner.json
  tokens/src/core/global/spacing.json
  tokens/src/core/global/transition.json
  tokens/src/core/global/typography.json
  tokens/src/themes/light/alias/color.json
Labels: blended

#2267 [BD-46] docs: refactoring Usage Insights
  www/gatsby-node.js
  www/src/components/insights/ComponentUsage.tsx
  www/src/components/insights/ComponentsUsage.tsx
  www/src/components/insights/HooksUsage.tsx
  www/src/components/insights/IconsUsage.tsx
  www/src/components/insights/ProjectsUsage.tsx
  www/src/components/insights/SummaryUsage.tsx
  www/src/components/insights/UtilsUsage.tsx
  www/src/context/InsightsContext.jsx
  www/src/pages/insights.tsx
  www/src/templates/component-page-template.tsx
  www/src/types/types.ts
  www/src/utils/componentsUsage.js
  www/src/utils/getDependentProjectsUsages.tsx
  www/src/utils/getEmptyMessage.tsx
  www/src/utils/getGithubProjectUrl.js
  www/src/utils/getParagonComponentsTypes.js
  www/src/utils/removeDotsFromKey.tsx
  www/src/utils/usagePropTypes.tsx
  www/utils/createCssUtilityClassNodes.js
  www/utils/createPages.js
  www/utils/onCreateNode.js
  www/utils/onCreateWebpackConfig.js
Labels: blended

#2393 [BD-46] fix: fixed Input is not defined in TransitionReplace component
  src/TransitionReplace/README.md
Labels: blended

#2394 [BD-46] docs: fixed links leading to React Bootstrap
  docs/decisions/0009-usage-of-react-bootstrap.rst
  src/Alert/README.md
  src/Badge/README.md
  src/Button/README.md
  src/Button/button-group.mdx
  src/Card/README.md
  src/Carousel/README.md
  src/Container/README.md
  src/Dropdown/README.md
  src/Figure/README.md
  src/Form/input-group.mdx
  src/Hyperlink/README.md
  src/Image/README.md
  src/Nav/README.md
  src/Navbar/README.md
  src/Overlay/README.md
  src/ProgressBar/README.md
  src/Spinner/README.md
  src/Tabs/README.md
  www/src/pages/foundations/layout.mdx
Labels: blended
