Repository openedx/paragon, pull requests merged in 2023-05, with the labels that each got.

#2230 feat(i18n) add new languages
  Makefile
  src/i18n/index.js
  src/i18n/messages/es_AR.json
  src/i18n/messages/es_ES.json
  src/i18n/messages/it_IT.json
  src/i18n/messages/pt_PT.json
  src/i18n/messages/tr_TR.json
  www/src/config.js
Labels: open-source-contribution

#2220 [BD-46] added Playroom
  .github/feedback_template.md
  package-lock.json
  src/Overlay/index.jsx
  www/gatsby-node.js
  www/package.json
  www/playroom.config.js
  www/playroom/FrameComponent.jsx
  www/playroom/scope.js
  www/playroom/snippets.js
  www/playroom/themes.js
  www/src/components/Header.tsx
  www/src/components/Menu.tsx
  www/src/components/PageLayout.tsx
  www/src/components/header/Header.scss
  www/src/components/header/Header.tsx
  www/src/components/header/Navbar.tsx
  www/src/components/header/SiteTitle.tsx
  www/src/components/header/index.js
  www/src/pages/playground.tsx
  www/src/scss/base.scss
  www/src/scss/edxorg-theme.scss
  www/src/scss/openedx-theme.scss
Labels: blended

#2252 [BD-46] docs: update README and fix feedback_template location
  .github/ISSUE_TEMPLATE/feedback_template.md
  README.md
  package.json
Labels: blended

#2251 [BD-46] docs: fixed paragon version view in dependent usage analyzer
  dependent-usage-analyzer/index.js
  www/src/components/insights/ComponentUsageExamples.tsx
  www/src/components/insights/ProjectUsageExamples.tsx
  www/src/components/insights/SummaryUsageExamples.tsx
  www/src/components/insights/UsagesList.tsx
  www/src/pages/insights.tsx
Labels: blended

#2201 [BD-46] docs: added Usage Insights on component page
  dependent-usage.json
  src/Card/README.md
  src/DataTable/README.md
  src/Dropdown/README.md
  src/Figure/README.md
  src/Form/README.md
  src/Form/form-radio.mdx
  src/Form/input-group.mdx
  src/Image/README.md
  src/Modal/modal-dialog.mdx
  src/Pagination/README.md
  src/Popover/README.md
  src/hooks/useArrowKeyNavigation.mdx
  src/hooks/useIndexOfLastVisibleChild.mdx
  src/hooks/useIsVisible.mdx
  src/hooks/useToggle.mdx
  src/hooks/useWindowSize.mdx
  www/src/pages/insights.tsx
  www/src/templates/component-page-template.tsx
Labels: blended

#1712 [BD-46] feat: Clickable steps in Stepper component
  src/Stepper/README.md
  src/Stepper/Stepper.scss
  src/Stepper/StepperContext.jsx
  src/Stepper/StepperHeader.jsx
  src/Stepper/StepperHeaderStep.jsx
  src/Stepper/StepperStep.jsx
  src/Stepper/tests/Stepper.test.jsx
Labels: blended

#2256 [BD-46] fix: added query-string package in the project
  package-lock.json
  www/package.json
Labels: blended

#2276 [BD-46] docs: renamed code example Segment event
  package-lock.json
  www/package.json
  www/src/components/CodeBlock.tsx
Labels: blended

#2283 [BD-46] fix: fixed Copy code example button
  www/src/components/CodeBlock.tsx
Labels: blended

#2279 [BD-46] fix: fixed bug with select state in SelectMenu component
  src/Menu/Menu.scss
  src/Menu/MenuItem.jsx
  src/Menu/SelectMenu.jsx
  src/Menu/__snapshots__/Menu.test.jsx.snap
  src/Menu/__snapshots__/MenuItem.test.jsx.snap
  src/Menu/__snapshots__/SelectMenu.test.jsx.snap
  src/Menu/_variables.scss
Labels: blended

#2272 feat: add `actions` prop to `Card.Status` and resolve few `Card`-related style issues
  src/Card/Card.scss
  src/Card/CardImageCap.jsx
  src/Card/CardStatus.jsx
  src/Card/README.md
  src/Card/tests/CardBody.test.jsx
  src/Card/tests/CardContext.test.jsx
  src/Card/tests/CardDeck.test.jsx
  src/Card/tests/CardGrid.test.jsx
  src/Card/tests/CardStatus.test.jsx
  src/Card/tests/__snapshots__/CardStatus.test.jsx.snap
  src/Dropzone/tests/Dropzone.test.jsx
  src/ProgressBar/tests/ProgressBar.test.jsx
  src/ProgressBar/tests/utils.test.js
  src/SelectableBox/tests/SelectableBox.test.jsx
  src/SelectableBox/tests/SelectableBoxSet.test.jsx
  src/SelectableBox/tests/utils.test.js
  src/StatusAlert/StatusAlert.test.jsx
Labels: emet

#2304 [BD-46] fix: use `currentTarget` in `FormAutosuggest` component to get selected option
  package.json
  src/Form/FormAutosuggest.jsx
  src/Form/form-autosuggest.mdx
  src/Modal/AlertModal.jsx
Labels: blended

#2222 [BD-46] feat: refactoring Tabs component
  src/Nav/Nav.scss
  src/Nav/_mixins.scss
  src/Nav/_variables.scss
  src/Tabs/README.md
  src/Tabs/Tabs.scss
  src/Tabs/Tabs.test.jsx
  src/Tabs/__snapshots__/Tabs.test.jsx.snap
  src/Tabs/_variables.scss
  src/Tabs/index.jsx
Labels: blended

#2291 [BD-46] feat: added variants for the Select Menu component
  src/Menu/SelectMenu.jsx
  src/Menu/SelectMenu.test.jsx
  src/Menu/__snapshots__/SelectMenu.test.jsx.snap
  src/Menu/select-menu.md
Labels: blended

#2316 [BD-46] build: upgrade netlify node version to 18
  netlify.toml
Labels: blended

#2313 [BD-46] docs: added Leave Feedback link
  www/src/components/LeaveFeedback.scss
  www/src/components/LeaveFeedback.tsx
  www/src/components/PageLayout.tsx
  www/src/scss/base.scss
Labels: blended

#2327 [BD-46] feat: finished FontAwesome deprecation
  package-lock.json
  package.json
  src/IconButton/README.md
  src/IconButton/__snapshots__/IconButton.test.jsx.snap
  src/IconButton/index.jsx
  www/package.json
Labels: blended

#2326 [BD-46] fix: fixed the Mailtolink variant in the Button component
  src/MailtoLink/index.jsx
Labels: blended

#2329 [BD-46] docs: added missing props on the documentation site
  src/Alert/index.jsx
  src/Button/deprecated/index.jsx
  src/Button/index.jsx
  src/Card/CardCarousel/CardCarouselSubtitle.jsx
  src/Card/index.jsx
  src/Collapsible/index.jsx
  src/DataTable/DataTableLayout.jsx
  src/Form/FormControlSet.jsx
  src/Form/FormRadioSet.jsx
  src/Modal/ModalLayer.jsx
  src/Nav/index.jsx
  src/OverflowScroll/OverflowScroll.jsx
  src/StatusAlert/index.jsx
  src/Tabs/index.jsx
  src/Toast/ToastContainer.jsx
  src/ValidationFormGroup/index.jsx
  www/src/components/header/Navbar.tsx
Labels: blended
