Repository openedx/paragon, pull requests merged in 2024-05, with the labels that each got.

#3026 fix: Wrong propTypes for SearchFieldAdvanced.icons
  src/SearchField/SearchFieldAdvanced.jsx
  src/SearchField/index.jsx
Labels: bug, open-source-contribution, byte-size

#3048 refactor: [BD-46] Revision of Core design token
  styles/css/core/variables.css
  styles/css/themes/light/variables.css
  styles/scss/core/_variables.scss
  styles/scss/core/core.scss
  tokens/src/core/alias/size.json
  tokens/src/core/components/Container.json
  tokens/src/core/global/display.json
  tokens/src/core/global/spacing.json
  tokens/src/themes/light/alias/color.json
  tokens/src/themes/light/components/general/input.json
  tokens/src/themes/light/components/general/link.json
  tokens/src/themes/light/components/general/list.json
  tokens/src/themes/light/components/general/text.json
Labels: blended

#3052 refactor: [BD-46] Revision of ChipCarousel-Pagination design token
  styles/css/core/variables.css
  styles/css/themes/light/variables.css
  tokens/src/core/components/ColorPicker.json
  tokens/src/core/components/Container.json
  tokens/src/core/components/DataTable.json
  tokens/src/core/components/Form/size.json
  tokens/src/core/components/Nav.json
  tokens/src/core/components/Pagination.json
  tokens/src/core/global/spacing.json
  tokens/src/themes/light/components/DataTable.json
  tokens/src/themes/light/components/Form/color.json
  tokens/src/themes/light/components/Form/elevation.json
  tokens/src/themes/light/components/Form/other.json
  tokens/src/themes/light/global/color.json
Labels: blended

#3075 docs: [BD-46] Updated Design tokens and Style dictionary documentation
  docs/decisions/0018-design-tokens-style-dictionary.rst
  docs/decisions/assets/design-tokens-style-dictionary.png
Labels: blended

#3051 refactor: [BD-46] Revision of ActionRow-Chip design token
  src/Button/index.scss
  src/Chip/index.scss
  src/Chip/mixins.scss
  src/Collapsible/index.scss
  styles/css/core/variables.css
  styles/css/themes/light/variables.css
  tokens/src/core/components/Breadcrumb.json
  tokens/src/core/components/Card.json
  tokens/src/core/components/Chip.json
  tokens/src/themes/light/components/Alert.json
  tokens/src/themes/light/components/Annotation.json
  tokens/src/themes/light/components/Avatar.json
  tokens/src/themes/light/components/Breadcrumb.json
  tokens/src/themes/light/components/Card.json
Labels: blended, design tokens

#3076 refactor: [BD-46] Component generator refactoring
  .stylelintignore
  README.md
  component-generator/constants.js
  component-generator/templates/_variables.scss
  component-generator/templates/index.scss
  tokens/README.md
  www/src/pages/tools/component-generator.mdx
Labels: blended

#3080 feat: add typings for <Button>
  package-lock.json
  package.json
  src/Button/Button.test.tsx
  src/Button/ButtonGroup.test.tsx
  src/Button/ButtonToolbar.test.tsx
  src/Button/__snapshots__/Button.test.tsx.snap
  src/Button/__snapshots__/ButtonGroup.test.tsx.snap
  src/Button/__snapshots__/ButtonToolbar.test.tsx.snap
  src/Button/index.tsx
  src/Chip/ChipIcon.tsx
  src/Chip/index.tsx
  src/Icon/index.d.ts
  src/Icon/index.jsx
  src/index.d.ts
  src/index.js
  src/utils/types/bootstrap.test.tsx
  src/utils/types/bootstrap.ts
  www/src/components/PageEditBtn/index.tsx
  www/src/components/header/Header.tsx
  www/src/components/header/Navbar.tsx
  www/tsconfig.json
Labels: open-source-contribution
